class IdsQuestions():
    def __init__(self):
        self.questions_list = ['När jag kände det som om jag svikit mig själv.\n',
                               ' När jag hade svårt att sova.\n', ' När jag kände mig nöjd och avspänd.\n',
                               ' När jag blev ledsen vid tanken på vad som hänt.\n',
                               ' När jag övertygade mig själv om att jag var en ny människa och kunde dricka alkohol / ta droger.\n',
                               ' När jag kom ihåg hur gott det smakade / skönt det kändes.\n',
                               ' När jag bråkade med en vän.\n',
                               ' När jag var ute med vänner och gick till en pub, restaurang o dyl.\n',
                               ' När jag ville höja min sexuella njutning.\n',
                               ' När andra människor inte verkade tycka om mig.\n', ' När jag var ensam.\n',
                               ' När jag var trött.\n', ' När jag hade roligt.\n',
                               ' När jag inte verkade kunna klara av saker som jag försökte göra.\n',
                               ' När jag började tro att alkohol /droger inte längre var ett problem för mig.\n',
                               ' När jag fick min favoritdryck som gåva / blev erbjuden min drog.\n',
                               ' När det var bråk hemma.\n',
                               ' När jag var i en situation som jag tidigare alltid brukade dricka / droga i.\n',
                               ' När jag kopplar av med en god vän och vill ha det trevligt.\n',
                               ' När någon som stod mig nära hade det svårt.\n',
                               ' När jag var rädd för att saker och ting inte skulle rätta till sig.\n',
                               ' När jag kände mig dåsig och ville hålla mig pigg.\n',
                               ' När allt verkade gå bra.\n',
                               ' När jag kände det som om det inte finns något annat kvar att göra.\n',
                               ' När jag undrade över min självkontroll över alkohol / droger, och det kändes som om jag måste sätta den på prov.\n',
                               ' När jag gick förbi en systembutik / langaren.\n',
                               ' När jag kände mig illa till mods tillsammans med någon.\n',
                               ' När jag var på fest och andra människor runt omkring mig drack / tog droger.\n',
                               ' När jag ville känna mig närmare någon jag tyckte om.\n',
                               ' När andra människor ingrep i mina planer.\n',
                               ' När jag kände mig mycket pressad.\n', ' När jag hade fysiska smärtor.\n',
                               ' När jag kände mig i toppform.\n', ' När jag kände mig tom invärtes.\n',
                               ' När jag kände mig säker på att jag kunde klara av lite alkohol / droger.\n',
                               ' När jag tänkte på hur härligt det skulle vara att dricka alkohol / hur skönt det skulle vara att ta droger.\n',
                               ' När det var problem med folk på jobbet.\n',
                               ' När någon annan drack / tog droger.\n',
                               ' När vänner brukade hälsa på och jag kände mig väl till mods.\n',
                               ' När jag kände mig osäker på om jag kunde motsvara människors förväntningar.\n',
                               ' När jag var arg på hur allt blivit.\n', ' När jag kände mig illamående.\n',
                               ' När jag kände mig tillfredsställd med något jag gjort.\n',
                               ' När jag var uttråkad.\n',
                               ' När jag började tänka att lite alkohol / droger kan väl inte skada.\n',
                               ' När jag oförutsett hittade droger / en flaska med min favoritdryck.\n',
                               ' När någon kritiserade mig.\n',
                               ' När jag var på restaurang och folk som var med mig beställde alkohol / plockade fram droger.\n',
                               ' När jag var ute på stan med mina vänner och ville öka nöjet.\n',
                               ' När det blev spänt på jobbet pga kraven från mina överordnade.\n',
                               ' När inte någonting av det som jag gjorde kändes rätt för mig.\n',
                               ' När jag kände mig utmattad.\n', ' När jag kände mig nöjd med livet.\n',
                               ' När allting gick dåligt för mig.\n',
                               ' När jag började känna det som om jag aldrig mer skulle kunna känna mina gränser vad gäller alkohol / droger om jag inte prövade dem.\n',
                               ' När jag såg någonting som påminde mig om drickande / drogande.\n',
                               ' När jag kände mig sexuellt avvisad.\n',
                               ' När jag blev erbjuden alkohol / droger och tyckte det var obehagligt att tacka nej.\n',
                               ' När jag pratade med någon och ville berätta en verkligt god historia.\n',
                               ' När jag kände mig svartsjuk eller avundsjuk på någon för vad han / hon gjort.\n',
                               ' När jag kände mig osäker på vad jag skulle göra.\n',
                               ' När min mage kändes som om den var en stor knut.\n',
                               ' När något trevligt inträffat och jag ville fira det.\n',
                               ' När jag började känna mig utled på livet.\n',
                               ' När jag ville bevisa för mig själv att jag kunde dricka alkohol / ta droger utan att bli påverkad.\n',
                               ' När jag helt plötsligt kände sug efter alkohol / droger.\n',
                               ' När folk omkring mig gjorde mig spänd och nervös.\n',
                               ' När jag mötte en vän och han / hon föreslog att vi skulle dricka alkohol / ta droger tillsammans.\n',
                               ' När jag ville fira med en vän.\n', ' När jag kände mig pressad av min familj.\n',
                               ' När jag kände det som om ingen egentligen brydde sig om vad som hände mig.\n',
                               ' När jag kände mig nervös och fysiskt spänd.\n',
                               ' När jag ville fira någon speciell händelse t ex födelsedag eller midsommar.\n',
                               ' När jag började känna mig skuldmedveten om något.\n',
                               ' När jag började tro att jag till sist var botad och nu kunde dricka alkohol / ta droger i måttliga mängder.\n',
                               ' När jag var i en situation, där jag vanligtvis brukar ta alkohol / droger.\n',
                               ' När jag kände mig oförmögen att uttrycka mina känslor.\n',
                               ' När någon ville pressa mig att ”vara en god kompis” och dricka alkohol / ta droger.\n',
                               ' När jag hade skoj med vänner och ville öka nöjet.\n',
                               ' När jag kände att jag behövde mod för att tala med någon.\n',
                               ' När jag kände mig ledsen och nere över saker och ting i allmänhet.\n',
                               ' När jag kände mig darrig och mådde illa.\n',
                               ' När jag kände på mig att allt skulle gå bra till slut.\n',
                               ' När jag hade problem och ville tänka klarare.\n',
                               ' När jag skulle försöka pröva min viljestyrka genom att visa att jag verkligen kunde sluta efter ett par glas / lite droger.\n',
                               ' När jag såg eller hörde något om min favoritdryck / drog i TV, på bio, i tidningar, böcker etc.\n',
                               ' När andra människor behandlade mig orättvist.\n',
                               ' När jag var och hälsade på hos någon och de bjöd mig på alkohol / droger.\n',
                               ' När jag hade roligt på en fest och ville känna mig ännu mer uppåt.\n',
                               ' När jag inte gick bra ihop med andra på jobbet.\n',
                               ' När jag kände mig osäker på mig själv och ville fungera bättre.\n',
                               ' När jag hade huvudvärk.\n',
                               ' När jag kände mig lycklig vid tanken på något som hade hänt.\n',
                               ' När jag tänkte på alla chanser jag missat i mitt liv.\n',
                               ' När jag började tänka att jag egentligen inte var beroende av alkohol / droger.\n',
                               ' När jag gick förbi en pub / langare.\n', ' När jag kände mig avvisad av vänner.\n',
                               ' När min chef bjöd mig på alkohol / droger.\n',
                               ' När jag njöt av en god måltid tillsammans med goda vänner och kände att jag ville göra det ännu trevligare.\n',
                               ' När jag kände att någon försökte styra mig och jag ville känna mig oberoende.\n',
                               ' Du har svarat på alla frågor, tryck "Nästa" för att se resultatet']

    def return_question(self, index):
        return self.questions_list[index]